# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('deadline', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
