# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160614_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 6, 14, 6, 25, 45, 786083, tzinfo=utc), max_length=50000),
            preserve_default=False,
        ),
    ]
