# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deadline',
            field=models.DateField(),
        ),
    ]
