# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160614_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='imgurl',
            field=models.ImageField(upload_to='images/%Y/%m/%d/%H/%s'),
        ),
    ]
