# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160614_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='imgurl',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
