# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160614_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.CharField(default='A10409008', max_length=20),
            preserve_default=False,
        ),
    ]
