# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_activity_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOINT_ACTIVITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('act_id', models.CharField(max_length=5)),
            ],
        ),
    ]
